version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  api:
    build:
      context: api
      dockerfile: Dockerfile
  dash:
    build:
      context: dash
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    environment:
      - DEBUG=0
      - API_URL=http://api:5000/api
    depends_on:
      - db
